[package]
name = "tool"
version = "0.1.0"
authors = ["Willy Svenningsson <willy@fager.st>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.3"
